services:
  - type: web
    name: outlook-automation
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
    healthCheckPath: /api/health