name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT || 22 }}
        script: |
          # Navigate to app directory
          cd /var/www/outlook-automation
          
          # Pull latest changes
          git pull origin main
          
          # Install/update dependencies
          npm ci --only=production
          
          # Restart application with PM2
          pm2 restart outlook-automation
          
          # Save PM2 configuration
          pm2 save
          
          # Check application status
          pm2 status
          
          # Test application health
          sleep 5
          curl -f http://localhost:5000/api/health || exit 1
          
          echo "✅ Deployment completed successfully!"

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Notify deployment result
      if: success()
      run: |
        echo "✅ Deployment to VPS completed successfully"
        
    - name: Notify deployment failure
      if: failure()
      run: |
        echo "❌ Deployment to VPS failed"
        exit 1